adlarge_fixtures_documentation:
  title: Documentation alice
  enableAutoDocumentation: true
  listenedCommand: hautelook:fixtures:load
  reloadCommands:
    - php bin/console doctrine:fixtures:load
  configEntities:
    Product:
      - id
      - name
      - owner
      - tags
    Customer:
      - firstname
      - lastname
      - email